// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbVidaUtil = new HashSet<tbVidaUtil>();
        }

        public int Cate_Id { get; set; }
        public string Cate_Descripcion { get; set; }
        public int? Cate_UsuarioCreacion { get; set; }
        public DateTime? Cate_FechaCreacion { get; set; }
        public int? Cate_UsuarioModificacion { get; set; }
        public DateTime? Cate_FechaModificacion { get; set; }

        public virtual tbUsuario Cate_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario Cate_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbVidaUtil> tbVidaUtil { get; set; }
    }
}