// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int EstD_Id { get; set; }
        public string EstD_Descripcion { get; set; }
        public int EstD_UsuarioCreacion { get; set; }
        public DateTime EstD_FechaCracion { get; set; }
        public int? EstD_UsuarioModificacion { get; set; }
        public DateTime? EstD_FechaModificacion { get; set; }

        public virtual tbUsuario EstD_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario EstD_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}