// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int EstD_Id { get; set; }
        public string EstD_Descripcion { get; set; }
        public int EstD_UsuarioCreacion { get; set; }
        public DateTime EstD_FechaCracion { get; set; }
        public int? EstD_UsuarioModificacion { get; set; }
        public DateTime? EstD_FechaModificacion { get; set; }
        public bool? EstD_Estado { get; set; }
        [Display(Name = "Usuario Creacion")]
        [NotMapped]
        public string Uuno { get; set; }
        [Display(Name = "Usuario Modificacion")]
        [NotMapped]
        public string Udos { get; set; }
        public virtual tbUsuario EstD_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario EstD_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}