// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public string Muni_Codigo { get; set; }
        public string Depa_Codigo { get; set; }
        public string Muni_Descripcion { get; set; }
        public int? Muni_UsuarioCreacion { get; set; }
        public DateTime? Muni_FechaCreacion { get; set; }
        public int? Muni_UsuarioModificacion { get; set; }
        public DateTime? Muni_FechaModificacion { get; set; }

        [Display(Name = "Usuario Creacion")]
        [NotMapped]
        public string Uuno { get; set; }
        [Display(Name = "Usuario Modificacion")]
        [NotMapped]
        public string Udos { get; set; }
        public virtual tbDepartamentos Depa_CodigoNavigation { get; set; }
        public virtual tbUsuario Muni_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario Muni_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}