// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int PaRo_Id { get; set; }
        public int? Role_Id { get; set; }
        public int? Pant_Id { get; set; }
        public int? PaRo_UsuarioCreacion { get; set; }
        public DateTime? PaRo_FechaCreacion { get; set; }
        public int? PaRo_UsuarioModificacion { get; set; }
        public DateTime? PaRo_FechaModificacion { get; set; }
        public bool? PaRo_Estado { get; set; }

        public virtual tbUsuario PaRo_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario PaRo_UsuarioModificacionNavigation { get; set; }
        public virtual tbPantallas Pant { get; set; }
        public virtual tbRoles Role { get; set; }
    }
}