// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaActivos.Entities.Entities
{
    public partial class tbSucursales
    {
        public int Sucu_Id { get; set; }
        public string Sucu_Descripcion { get; set; }
        public string Depa_Codigo { get; set; }
        public string Muni_Codigo { get; set; }
        public string Sucu_DireccionExacta { get; set; }
        public int Sucu_UsuarioCreacion { get; set; }
        public DateTime Sucu_FechaCreacion { get; set; }
        public int? Sucu_UsuarioModificacion { get; set; }
        public DateTime? Sucu_FechaModificacion { get; set; }
        public bool? Sucu_Estado { get; set; }
        [NotMapped]
        public string Depa_Descripcion { get; set; }
        [NotMapped]
        public string Muni_Descripcion { get; set; }
        [Display(Name = "Usuario Creacion")]
        [NotMapped]
        public string Uuno { get; set; }
        [Display(Name = "Usuario Modificacion")]
        [NotMapped]
        public string Udos { get; set; }
        public virtual tbDepartamentos Depa_CodigoNavigation { get; set; }
        public virtual tbMunicipios Muni_CodigoNavigation { get; set; }
        public virtual tbUsuario Sucu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario Sucu_UsuarioModificacionNavigation { get; set; }
    }
}