// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaActivos.Entities
{
    public partial class tbActivos
    {
        public int Acti_Id { get; set; }
        public string Acti_Url { get; set; }
        public string Acti_Descripcion { get; set; }
        public decimal? Acti_Precio { get; set; }
        public string Acti_Marca { get; set; }
        public string Acti_Modelo { get; set; }
        public string Acti_NoSerio { get; set; }
        public int? Empl_Id { get; set; }
        public int? VidU_Id { get; set; }
        public DateTime? Acti_FechaAdquisicion { get; set; }
        public int? Acti_UsuarioCreacion { get; set; }
        public DateTime? Acti_FechaCreacion { get; set; }
        public int? Acti_UsuarioModificacion { get; set; }
        public DateTime? Acti_FechaModificacion { get; set; }
        public bool? Acti_Estado { get; set; }

        public virtual tbUsuario Acti_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario Acti_UsuarioModificacionNavigation { get; set; }
        public virtual tbEmpleados Empl { get; set; }
        public virtual tbVidaUtil VidU { get; set; }
    }
}