// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaActivos.Entities
{
    public partial class tbCargos
    {
        public int Carg_Id { get; set; }
        public string Carg_Descripcion { get; set; }
        public int? Carg_UsuarioCreacion { get; set; }
        public DateTime? Carg_FechaCreacion { get; set; }
        public int? Carg_UsuarioModificacion { get; set; }
        public DateTime? Carg_FechaModificacion { get; set; }
        public bool? Carg_Estado { get; set; }

        public virtual tbUsuario Carg_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuario Carg_UsuarioModificacionNavigation { get; set; }
    }
}